version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/nestdb?schema=public"
      NODE_ENV: development
    depends_on:
      - postgres
    command: sh -c "npx prisma generate && npx prisma migrate dev && npm run start:dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "5173:80"
    environment:
      - REACT_APP_API_URL=http://backend:3000
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: nest-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: